version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: orsproject10-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orsproject10
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - ./mysql-data:/var/lib/mysql
  webapp:
    build:
      context: .
    container_name: orsproject10-webapp
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=jdbc:mysql://localhost:3307/orsproject10
networks:
  mynetwork:
    driver: bridge